#EEASYXB_SOURCE variable pointing to this directory
#must be declared in the root level project Makefile 
#and this file should be included.

CXXFLAGS  += -I$(EEASYXB_SOURCE)
CXXFLAGS  += -I$(EEASYXB_SOURCE)/Types

SRCS += $(EEASYXB_SOURCE)/Eeprom.cpp